# Pintos 用户态 doom 构建。
# 用法: 在 doomgeneric 目录下 make -f Makefile.pintos
# 产物: doom(链接进 threads/build 的 libc.a 和 entry.o)
#
# 注意: 链接必须带 -z noseparate-code,否则 binutils 会把 ELF 头
# 做成独立 LOAD 段,与主代码段同页,Pintos 加载器会静默加载失败。

CC = gcc
SRCDIR = ..
LIBDIR = $(SRCDIR)/lib
USERLIB = $(LIBDIR)/user
BUILD = $(SRCDIR)/threads/build

CFLAGS = -m32 -ggdb3 -O2 -march=i686 -fno-pic -fno-stack-protector \
         -nostdinc -Ishim -I$(SRCDIR) -I$(LIBDIR) -I$(USERLIB) -I. -Wall
LDFLAGS = -m32 -z noseparate-code -Wl,--build-id=none -nostdlib -static \
          -Wl,-T,$(USERLIB)/user.lds

SRCS = dummy.c am_map.c doomdef.c doomstat.c dstrings.c d_event.c \
  d_items.c d_iwad.c d_loop.c d_main.c d_mode.c d_net.c f_finale.c \
  f_wipe.c g_game.c hu_lib.c hu_stuff.c info.c i_cdmus.c i_endoom.c \
  i_joystick.c i_scale.c i_sound.c i_system.c i_timer.c memio.c \
  m_argv.c m_bbox.c m_cheat.c m_config.c m_controls.c m_fixed.c \
  m_menu.c m_misc.c m_random.c p_ceilng.c p_doors.c p_enemy.c \
  p_floor.c p_inter.c p_lights.c p_map.c p_maputl.c p_mobj.c \
  p_plats.c p_pspr.c p_saveg.c p_setup.c p_sight.c p_spec.c \
  p_switch.c p_telept.c p_tick.c p_user.c r_bsp.c r_data.c r_draw.c \
  r_main.c r_plane.c r_segs.c r_sky.c r_things.c sha1.c sounds.c \
  statdump.c st_lib.c st_stuff.c s_sound.c tables.c v_video.c \
  wi_stuff.c w_checksum.c w_file.c w_main.c w_wad.c z_zone.c \
  w_file_stdc.c i_input.c i_video.c doomgeneric.c mus2mid.c \
  doom_pintos.c pintos_platform.c

OBJS = $(SRCS:.c=.o)

all: doom

doom: $(OBJS) $(BUILD)/lib/user/entry.o $(BUILD)/libc.a
	$(CC) $(LDFLAGS) $(OBJS) $(BUILD)/lib/user/entry.o $(BUILD)/libc.a -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# 平台层定义了 malloc/calloc/free 本身;-O2 下 gcc 会把
# "malloc+memset(0)" 优化成对 calloc 的调用,在我们自己的
# calloc 里变成无限自递归。必须禁用 builtin 优化。
pintos_platform.o: pintos_platform.c
	$(CC) $(CFLAGS) -fno-builtin -c $< -o $@

clean:
	rm -f $(OBJS) doom

.PHONY: all clean
